sudo: required
dist: trusty

language: cpp
os: linux
compiler: gcc

branches:
  only:
    - master

addons:
  apt:
    packages:
      - m4
      - zlib1g-dev
      - build-essential
      - libbz2-dev
      - libgmp3-dev

script:
  - cd bncsutil/src/bncsutil && make && sudo make install
  - cd gproxy && make
