sudo: required

branches:
  only:
    - master

language: cpp
os: linux
compiler: gcc

before_install:
  - sudo apt-get update --fix-missing
  - sudo apt-get install build-essential m4 zlib1g-dev libbz2-dev libgmp3-dev automake

script:
  - cd bncsutil/src/bncsutil && make && sudo make install
  - cd ../../../gproxy && make
